import { HospitalBloodBank } from "@/types/database";

export const ALL_STATES = [
  "Andhra Pradesh",
  "Telangana",
  "Karnataka",
  "Maharashtra",
  "Tamil Nadu",
  "Delhi NCR",
  "West Bengal",
  "Gujarat",
  "Rajasthan",
  "Kerala",
] as const;

export const ANDHRA_PRADESH_CITIES = [
  "Visakhapatnam",
  "Vijayawada",
  "Guntur",
  "Tirupati",
  "Kurnool",
  "Nellore",
  "Rajahmundry",
  "Kakinada",
  "Anantapur",
  "Kadapa",
  "Eluru",
  "Ongole",
  "Vizianagaram",
  "Machilipatnam",
  "Srikakulam",
  "Chittoor",
];

export const ALL_CITIES_BY_STATE: Record<string, string[]> = {
  "Andhra Pradesh": ANDHRA_PRADESH_CITIES,
  "Telangana": ["Hyderabad", "Secunderabad", "Warangal", "Nizamabad", "Karimnagar"],
  "Karnataka": ["Bengaluru", "Mysuru", "Hubballi-Dharwad", "Mangaluru", "Belagavi"],
  "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"],
  "Delhi NCR": ["Delhi", "New Delhi", "Noida", "Gurugram", "Faridabad"],
  "West Bengal": ["Kolkata", "Howrah", "Siliguri", "Durgapur", "Asansol"],
  "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"],
  "Rajasthan": ["Jaipur", "Jodhpur", "Kota", "Udaipur", "Ajmer"],
  "Kerala": ["Kochi", "Thiruvananthapuram", "Kozhikode", "Thrissur", "Kollam"],
};

export const HOSPITAL_AND_BLOOD_BANKS: HospitalBloodBank[] = [
  // --- ANDHRA PRADESH: VISAKHAPATNAM (VIZAG) ---
  {
    id: "ap-viz-001",
    name: "King George Hospital (KGH) Government Blood Bank",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Andhra Pradesh",
    city: "Visakhapatnam",
    district: "Visakhapatnam",
    address: "Maharanipeta, Collector Office Junction, Visakhapatnam",
    pincode: "530002",
    phone: "+91 891 2564891",
    helpline: "104 / 108",
    componentsAvailable: ["Whole Blood", "Packed Red Blood Cells (PRBC)", "Fresh Frozen Plasma (FFP)", "Platelet Concentrate (RDP)"],
    operatingHours: "24x7 Emergency Services",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-viz-002",
    name: "Care Hospital Blood Centre & Component Unit",
    type: "Super Specialty Hospital Blood Centre",
    state: "Andhra Pradesh",
    city: "Visakhapatnam",
    district: "Visakhapatnam",
    address: "AS Raja Complex, Waltair Main Road, Ram Nagar, Visakhapatnam",
    pincode: "530003",
    phone: "+91 891 3041444",
    componentsAvailable: ["Whole Blood", "PRBC", "Single Donor Platelets (SDP)", "FFP", "Cryoprecipitate"],
    operatingHours: "24x7 Emergency Services",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-viz-003",
    name: "Apollo Hospitals Blood Bank (Health City)",
    type: "Super Specialty Hospital Blood Centre",
    state: "Andhra Pradesh",
    city: "Visakhapatnam",
    district: "Visakhapatnam",
    address: "Plot No. 1, Health City, Chinagadila, Arilova, Visakhapatnam",
    pincode: "530040",
    phone: "+91 891 2727272",
    componentsAvailable: ["Whole Blood", "PRBC", "SDP (Apheresis)", "FFP"],
    operatingHours: "24x7 Round the Clock",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-viz-004",
    name: "Rotary Blood Bank & Charitable Component Centre",
    type: "Rotary Blood Bank",
    state: "Andhra Pradesh",
    city: "Visakhapatnam",
    district: "Visakhapatnam",
    address: "Rotary Seva Sadan, 28-2-47, Daba Gardens, Visakhapatnam",
    pincode: "530020",
    phone: "+91 891 2563388",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP", "Platelet Concentrates"],
    operatingHours: "24 Hours Open",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },

  // --- ANDHRA PRADESH: VIJAYAWADA ---
  {
    id: "ap-vja-001",
    name: "Government General Hospital (GGH) Old & New Blood Bank",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Andhra Pradesh",
    city: "Vijayawada",
    district: "NTR District",
    address: "Siddhartha Medical College Campus, Ring Road, Gunadala, Vijayawada",
    pincode: "520008",
    phone: "+91 866 2451234",
    helpline: "104",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP", "Platelet Rich Plasma (PRP)"],
    operatingHours: "24x7 Round the Clock",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-vja-002",
    name: "Indian Red Cross Society Blood Centre Vijayawada",
    type: "Red Cross Society Blood Centre",
    state: "Andhra Pradesh",
    city: "Vijayawada",
    district: "NTR District",
    address: "Red Cross Building, Bandar Road, Governorpet, Vijayawada",
    pincode: "520002",
    phone: "+91 866 2577666",
    componentsAvailable: ["Whole Blood", "PRBC", "Platelet Concentrates", "FFP"],
    operatingHours: "24 Hours Service",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-vja-003",
    name: "Manipal Hospital Blood Centre Vijayawada",
    type: "Super Specialty Hospital Blood Centre",
    state: "Andhra Pradesh",
    city: "Vijayawada",
    district: "Guntur / NTR Border",
    address: "NH-16, Near Kanakadurga Varadhi, Tadepalli, Vijayawada Region",
    pincode: "522501",
    phone: "+91 8645 350000",
    componentsAvailable: ["Whole Blood", "PRBC", "Single Donor Platelets (SDP)", "FFP"],
    operatingHours: "24x7 Emergency Blood Bank",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-vja-004",
    name: "Ramesh Hospitals Blood Centre",
    type: "Super Specialty Hospital Blood Centre",
    state: "Andhra Pradesh",
    city: "Vijayawada",
    district: "NTR District",
    address: "Collector Office Road, Ring Road, Vijayawada",
    pincode: "520008",
    phone: "+91 866 2488888",
    componentsAvailable: ["Whole Blood", "PRBC", "Platelet Apheresis", "FFP"],
    operatingHours: "24 Hours Open",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },

  // --- ANDHRA PRADESH: GUNTUR ---
  {
    id: "ap-gun-001",
    name: "Government General Hospital (GGH) Guntur Blood Bank",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Andhra Pradesh",
    city: "Guntur",
    district: "Guntur",
    address: "Opposite Market Yard, Sambasiva Pet, Guntur",
    pincode: "522001",
    phone: "+91 863 2220033",
    helpline: "104",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP", "Random Donor Platelets (RDP)"],
    operatingHours: "24x7 Emergency Services",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-gun-002",
    name: "AIIMS Mangalagiri Central Blood Centre",
    type: "Autonomous Medical Institute",
    state: "Andhra Pradesh",
    city: "Guntur",
    district: "Guntur",
    address: "All India Institute of Medical Sciences, Mangalagiri, Guntur District",
    pincode: "522503",
    phone: "+91 8645 280000",
    componentsAvailable: ["Whole Blood", "PRBC", "Single Donor Platelets (SDP)", "FFP", "Cryoprecipitate"],
    operatingHours: "24x7 Round the Clock",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-gun-003",
    name: "NRI General Hospital & Medical College Blood Bank",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Andhra Pradesh",
    city: "Guntur",
    district: "Guntur",
    address: "Chinakakani, Mangalagiri Mandal, Guntur District",
    pincode: "522503",
    phone: "+91 8645 230101",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP", "Platelet Concentrates"],
    operatingHours: "24 Hours Open",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },

  // --- ANDHRA PRADESH: TIRUPATI ---
  {
    id: "ap-tir-001",
    name: "Sri Venkateswara Institute of Medical Sciences (SVIMS) Blood Bank",
    type: "Autonomous Medical Institute",
    state: "Andhra Pradesh",
    city: "Tirupati",
    district: "Tirupati",
    address: "SVIMS Hospital Campus, Alipiri Road, Tirupati",
    pincode: "517507",
    phone: "+91 877 2287777",
    helpline: "104 / 108",
    componentsAvailable: ["Whole Blood", "PRBC", "Apheresis Platelets (SDP)", "FFP", "Cryo"],
    operatingHours: "24x7 Emergency Services",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-tir-002",
    name: "SVRR Government General Hospital (Ruia Hospital) Blood Bank",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Andhra Pradesh",
    city: "Tirupati",
    district: "Tirupati",
    address: "Alipiri Bypass Road, Near Ruia Hospital, Tirupati",
    pincode: "517501",
    phone: "+91 877 2286666",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP", "Platelet Concentrates"],
    operatingHours: "24x7 Round the Clock",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-tir-003",
    name: "Indian Red Cross Society Blood Centre Tirupati",
    type: "Red Cross Society Blood Centre",
    state: "Andhra Pradesh",
    city: "Tirupati",
    district: "Tirupati",
    address: "Red Cross Bhawan, Balaji Colony, Tirupati",
    pincode: "517502",
    phone: "+91 877 2225588",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP"],
    operatingHours: "24 Hours Service",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },

  // --- ANDHRA PRADESH: KURNOOL ---
  {
    id: "ap-kur-001",
    name: "Government General Hospital (GGH) Kurnool Blood Centre",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Andhra Pradesh",
    city: "Kurnool",
    district: "Kurnool",
    address: "Medical College Road, Budhawara Peta, Kurnool",
    pincode: "518002",
    phone: "+91 8518 255100",
    helpline: "104",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP", "Platelet Concentrates"],
    operatingHours: "24x7 Round the Clock",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },

  // --- ANDHRA PRADESH: NELLORE ---
  {
    id: "ap-nel-001",
    name: "ACSR Government Medical College & Hospital Blood Bank",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Andhra Pradesh",
    city: "Nellore",
    district: "SPSR Nellore",
    address: "Dargamitta, Near ACSR Medical College, Nellore",
    pincode: "524004",
    phone: "+91 861 2315000",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP", "Platelet Concentrates"],
    operatingHours: "24 Hours Open",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-nel-002",
    name: "Narayana Medical College & Super Specialty Hospital Blood Centre",
    type: "Super Specialty Hospital Blood Centre",
    state: "Andhra Pradesh",
    city: "Nellore",
    district: "SPSR Nellore",
    address: "Chinthareddypalem, Nellore",
    pincode: "524003",
    phone: "+91 861 2317963",
    componentsAvailable: ["Whole Blood", "PRBC", "SDP Platelets", "FFP"],
    operatingHours: "24x7 Emergency Blood Bank",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },

  // --- ANDHRA PRADESH: RAJAHMUNDRY & KAKINADA ---
  {
    id: "ap-raj-001",
    name: "Government District Hospital Blood Centre Rajahmundry",
    type: "District General Hospital Blood Centre",
    state: "Andhra Pradesh",
    city: "Rajahmundry",
    district: "East Godavari",
    address: "Main Road, Near Kotipalli Bus Stand, Rajahmundry",
    pincode: "533101",
    phone: "+91 883 2442233",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP"],
    operatingHours: "24x7 Round the Clock",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-kak-001",
    name: "Rangaraya Medical College & GGH Blood Centre Kakinada",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Andhra Pradesh",
    city: "Kakinada",
    district: "Kakinada",
    address: "Pithapuram Road, Near Collectorate, Kakinada",
    pincode: "533001",
    phone: "+91 884 2373300",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP", "Platelet Concentrates"],
    operatingHours: "24x7 Open",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },

  // --- ANDHRA PRADESH: ANANTAPUR & KADAPA ---
  {
    id: "ap-atp-001",
    name: "Government General Hospital (GGH) Blood Bank Anantapur",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Andhra Pradesh",
    city: "Anantapur",
    district: "Anantapur",
    address: "Court Road, Government Medical College Campus, Anantapur",
    pincode: "515001",
    phone: "+91 8554 275522",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP"],
    operatingHours: "24 Hours Open",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "ap-kad-001",
    name: "Rajiv Gandhi Institute of Medical Sciences (RIMS) Blood Centre Kadapa",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Andhra Pradesh",
    city: "Kadapa",
    district: "YSR Kadapa",
    address: "Putlampalli, RIMS Hospital Campus, Kadapa",
    pincode: "516002",
    phone: "+91 8562 220200",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP", "Platelet Concentrates"],
    operatingHours: "24x7 Emergency Services",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },

  // --- NATIONAL METRO HOSPITALS & BLOOD BANKS ---
  {
    id: "nat-del-001",
    name: "AIIMS Main Blood Bank New Delhi",
    type: "Autonomous Medical Institute",
    state: "Delhi NCR",
    city: "Delhi",
    district: "South Delhi",
    address: "Ansari Nagar East, Ring Road, New Delhi",
    pincode: "110029",
    phone: "+91 11 26588500",
    helpline: "108 / 104",
    componentsAvailable: ["Whole Blood", "PRBC", "SDP", "FFP", "Cryoprecipitate", "Granulocytes"],
    operatingHours: "24x7 Continuous Operation",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "nat-mum-001",
    name: "Tata Memorial Hospital Blood Centre Mumbai",
    type: "Autonomous Medical Institute",
    state: "Maharashtra",
    city: "Mumbai",
    district: "Mumbai City",
    address: "Dr. Ernest Borges Marg, Parel, Mumbai",
    pincode: "400012",
    phone: "+91 22 24177000",
    componentsAvailable: ["Whole Blood", "PRBC", "Single Donor Platelets", "FFP", "Irradiated Blood Components"],
    operatingHours: "24x7 Dedicated Oncology Blood Services",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "nat-blr-001",
    name: "Victoria Hospital Central Blood Bank / BMCRI Bengaluru",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Karnataka",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    address: "Fort Road, Near City Market, Bengaluru",
    pincode: "560002",
    phone: "+91 80 26701150",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP", "Platelet Concentrates"],
    operatingHours: "24x7 Round the Clock",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "nat-hyd-001",
    name: "Osmania General Hospital Blood Bank Hyderabad",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Telangana",
    city: "Hyderabad",
    district: "Hyderabad",
    address: "Afzal Gunj, High Court Road, Hyderabad",
    pincode: "500012",
    phone: "+91 40 24600121",
    componentsAvailable: ["Whole Blood", "PRBC", "FFP", "Platelet Concentrates"],
    operatingHours: "24x7 Open",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
  {
    id: "nat-chn-001",
    name: "Rajiv Gandhi Government General Hospital (RGGGH) Blood Bank Chennai",
    type: "Govt Medical College & Hospital Blood Bank",
    state: "Tamil Nadu",
    city: "Chennai",
    district: "Chennai",
    address: "EVR Periyar Salai, Park Town, Chennai",
    pincode: "600003",
    phone: "+91 44 25305000",
    componentsAvailable: ["Whole Blood", "PRBC", "SDP", "FFP", "Cryoprecipitate"],
    operatingHours: "24 Hours Service",
    isGovernmentCertified: true,
    eRaktKoshRegistered: true,
  },
];
